### ISSUE TITLE
Research Spike - Aphrodite / Inline Styles

### ISSUE THREAD

**Issue by gabeweaver** [verypossible/booster-kit-react#26]
By using inline styles with JS for styling components, we will have better parity and reusability between web and mobile environments. 

Suggested Approach:

- [x] Install [Aphrodite](https://github.com/Khan/aphrodite) but see if they have native support for gracefully handling global styles as [discussed here](https://medium.com/front-end-hacking/scalable-styles-in-production-js-cde88016f357#.q1jtut8al)
- [x] Style a few components with it and see how it goes

**Comment by TheAznShumai** [comment]
So this lib works pretty well.  It does exactly what it said it does and can handle global styles after creating a selecthandler extension.  The github documentation can be a bit confusing.  If you want to try it out a better example is located at
https://github.com/Khan/aphrodite/issues/139

From post https://medium.com/front-end-hacking/scalable-styles-in-production-js-cde88016f357
I tried getting the alternative solution for global styles from to work; but it proved difficult.  His points on potential issues with the global styles on this lib is still valid.  You may run into issues with conflicting styles depending on the setup that we are introducing.

Animations work as documentations states and as far as server side rendering goes for this item, I haven't tested it out.

TTD - Final Thoughts
Its pretty cool.
