### ISSUE TITLE
Migrate to Nightwatch.js for feature specs

### ISSUE THREAD

**Issue by tpalmer** [verypossible/booster-kit-react#27]
We should port the feature spec changes made to the thrive-marketing repository to here.

[Nightwatch.js](http://nightwatchjs.org/)

**Comment by gabeweaver** [comment]
@tpalmer so Nightmare is not correctly configured here...

The root problem is how we're initializing a single nightmare instance and then trying to use that one instance to run all acceptance tests. You can [read about why that's problematic](https://github.com/rosshinkley/nightmare-examples/blob/master/docs/common-pitfalls/async-operations-loops.md), but given correctly initializing nightmare, it seems like a better route given that it's a little more actively maintained and doesn't require version controlling  a 20+ mb file.

See how i set it up [with foresight](https://github.com/spartansystems/foresight-client/tree/master/tests/features). By keeping the browser actions in their own directory, you can easily include one or more actions to string together end to end tests. Each action imports an instance of nightmare, and each can return a promise...so you can easily string them together and wrap them with Jest. 

A side benefit, when run with Yarn...test times for 3-5 feature tests went from 30-40sec to 3-5 sec. 

Thoughts?

**Comment by bbrock25** [comment]
@gabeweaver It would be interesting to see if this updated approach would actually improve the performance of the specs in thrive. I'm pretty sure that @tpalmer tried creating a nightmare instance for each spec, in attempt to debug this. Is that correct? If not, it could be worth a spike. Does anyone care to own that? 

In my experience, I found that I enjoyed writing the nightwatch tests more than nightmare and it was actually beneficial to have it running outside of jest from a configuration management standpoint. We currently have 53 feature specs and while they are not the "fastest" the bottleneck isn't the runner as much as it is the interactions with the api. 

Either way, our approach needs to be documented. It would be good blog post material, just saying...

**Comment by tpalmer** [comment]
On Thrive we tried for quite a while to get Nightmare into a consistent and reliable state, and we didn't have much luck.  We tried instantiating a separate Nightmare instance per-test, so they run synchronously, and that still had timeout issues.  Ultimately we refactored everything to use Nightwatch, and so far the tests are significantly more reliable - plus we get the added benefit of multiple browser testing if desired.

The problems arose when we started having more than a handful of tests, so I'm curious if you'll run into the same issues on Foresight or not.

As far as what we adopt for the booster kit, I ultimately don't care, as long as it works consistently and reliably.  The Thrive case study seems to indicate that Nighwatch is the more robust solution, but I'm open to alternatives.

**Comment by gabeweaver** [comment]
I haven't run into a single timeout issue that wasn't the direct result of an incorrectly test on my part...

I'd like to continue writing tests with Nightmare until we run into an issue on the booster or foresight that demonstrates it is inferior to nightwatch.

I have a hard time believing that given Nightmare has twice the contributors and stars than Nightwatch...

I can pair with someone on to retrofit Thrive with nightmare running correctly and we can measure performance..but thats an optimization to make the car go faster when we don't even have a car yet.

**Comment by gabeweaver** [comment]
@tpalmer do you want to run a benchmark between the two or are you ok if i just close this? We haven't run into any issues with Nightmare in the last few months...

**Comment by tpalmer** [comment]
I'm fine with whatever works consistently!  It sounds like Nightmare could work fine.
